language: perl
perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

env: AUTHOR_TESTING=1 RELEASE_TESTING=1
install: cpanm --quiet --notest Dist::Zilla Dancer2 Dancer2::Plugin Pod::Coverage::TrustPod && (dzil authordeps --missing; dzil listdeps --missing) | cpanm --quiet --notest
script: dzil test
