language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

env: AUTHOR_TESTING=1 RELEASE_TESTING=1
install: cpanm --quiet --notest Dancer2 Dancer2::Plugin Pod::Coverage::TrustPod && dzil authordeps --missing | cpanm --quiet --notest
script: dzil build && dzil test
