language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

env: AUTHOR_TESTING=1 RELEASE_TESTING=1
install: cpanm --quiet --installdeps --notest Dancer2 && dzil authordeps --missing | cpanm --quiet --notest
script: dzil build && dzil test
